version: '3.8'

services:
  # --- REVERSE PROXY SÉCURISÉ ---
  proxy:
    image: nginx:alpine
    container_name: socket-nginx
    ports:
      - "80:80" # C'est le SEUL port ouvert sur l'extérieur (Hardening)
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - api
    networks:
      - socket_network

  # --- 1. FRONT-END (Dashboard) ---
  web:
    build: ./frontend
    container_name: socket-frontend
    # Ports retirés : segmentation réseau stricte, invisible de l'extérieur
    depends_on:
      - api
    networks:
      - socket_network

  # --- 2. BACK-END (API Python) ---
  api:
    build: ./backend
    container_name: socket-backend
    # Ports retirés : segmentation réseau stricte, invisible de l'extérieur
    depends_on:
      - db-sql
      - db-nosql
    networks:
      - socket_network

  # --- 3. BASE DE DONNÉES SQL (PostgreSQL) ---
  db-sql:
    image: postgres:15
    container_name: socket-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: StrongPassword123!
      POSTGRES_DB: socket_db
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - socket_network

  # --- 4. BASE DE DONNÉES NOSQL (Elasticsearch) ---
  db-nosql:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: socket-elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=StrongElasticPass123!
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Bridage de la RAM pour éviter le crash (Code 137)
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - socket_network

# Création d'un réseau privé pour isoler nos conteneurs
networks:
  socket_network:
    driver: bridge

# Persistance des données pour le PCA/PRA
volumes:
  pgdata:
  esdata: