server {
    listen 80;
    server_name localhost;

    # ==========================================
    # EN-TÊTES DE SÉCURITÉ (HARDENING)
    # ==========================================
    # Empêche le Clickjacking
    add_header X-Frame-Options "SAMEORIGIN";
    # Bloque le chargement en cas de détection de faille XSS
    add_header X-XSS-Protection "1; mode=block";
    # Empêche le navigateur de deviner le type de fichier (MIME sniffing)
    add_header X-Content-Type-Options "nosniff";
    # Ne pas divulguer la version de Nginx
    server_tokens off;

    # ==========================================
    # SEGMENTATION RÉSEAU
    # ==========================================
    # Redirection vers le Front-end (Vue.js)
    location / {
        proxy_pass http://web:5173;
    }

    # Redirection vers l'API Back-end (FastAPI)
    location /api/ {
        proxy_pass http://api:8000/;
    }
}